# Custom Favicon
favicon: /assets/images/content/favicon.png
# Site name
name: Linaro
# Support for http2 push features
http2: true
# Hide last modified at date
hide_last_modified: true
# Support for http2 push features
http2_resources:
  - rel: preload
    as: image
    href: /assets/images/Linaro-Sprinkle.png
# Ascii Art
ascii-art: ascii-art.html
# Site Slogan
slogan: Accelerating deployment of Arm-based solutions
# Mailchimp settings
mailchimp:
    enabled: true
    id: af6cf590b0
    unsubscribe-url: https://linaro.us3.list-manage.com/unsubscribe?u=14baaae786342d0d405ee59c2&id=af6cf590b0
# Footer Newsletter toggle.
newsletter:
    enabled: true
    url: https://linaro.us3.list-manage.com/subscribe/post?u=14baaae786342d0d405ee59c2&amp;id=af6cf590b0
tags_enabled: true
jumbotron:
  darken: true
# Footer Image default is linaro sprinkle
linaro-footer-image: Linaro-Sprinkle.png
# # Breadcrumb Settings
# breadcrumb:
#     image: breadcrumb-image.jpg
#Content Repo for static site.
# Used for the edit on github include
edit-on-github:
    enabled: true
    repo: https://www.github.com/Linaro/website
# Settings for the home page
home:
    #Content Background Image E.g. DeviceTree.org
    # content-image: background-image.png
    # If this is set then the navigation will be transparent.
    transparent-nav: true
    # If this is set to true then the shape divider will be displayed
    shaped-divider: false
    # Jumbotron settings for the home page
    jumbotron:
        # Include file to replace all the contents of the jumbotron with.
        included_file: hero-banner.html
        # Toggle the jumbotron
        enabled: true
        # Background image for the home page located in assets/images
        background-image:
            # Darken is set to true by default - if you wish to remove the image overlay
            # then change this setting to false.
            darken: true
            # This is the name of the background-image located in /assets/images/
            name: hkg18-tech-banner.jpg
        # image: devicetree-icon-white.png
# Jekyll social media site settings. Github, LinkedIn, Google+, Facebook and Youtube
github_username: Linaro
linkedin_username: 1026961
facebook_username: LinaroOrg
youtube_username: linaroorg
twitter_username: linaroorg
slideshare_username: linaroorg
# Blog setup
blog:
    # Url for the blog tags page
    tags_page: /blog/tag/
    # Show Thumbnails in the post index
    show_thumbnails: true
    # Toggle the output of blog/news reading time.
    reading_time: true
    # Toggle site wide comments display.
    comments: true
    # Post Side Bar Settings
    sidebar:
        display-on-posts: true
        display-on-index: true
        # Toggle whether or not thumbnails in the sidebar are displayed.
        thumbnails:
            display: true
        # Display other posts contained in _posts
        other-posts:
            display: true
            count: 4
        # Display Related posts based on tags / categories
        related-posts:
            display: true
            count: 5
        # Display the most recent posts
        most-recent-posts:
            display: true
            count: 5
        # Display custom collection e.g projects on 96boards
        collection:
            - name: projects
              count: 5
              # Fields to use for title and url.
              display_fields:
                  title: title
                  url: url
# Google Anayltics Setup
google_analytics:
    production: UA-16756069-1
# Shema.org settings used in the schema.html include.
schema:
    enabled: false
    organisation:
        name: Linaro
        url: https://www.linaro.org
        sameAs:
            - https://twitter.com/linaroorg
            - https://www.facebook.com/LinaroOrg
            - https://www.linkedin.com/company/1026961/
            - https://plus.google.com/+LinaroOnAir
            - https://github.com/Linaro
            - https://www.slideshare.net/linaroorg
        address:
            street: Harston Mill, Royston Rd
            town: Harston
            county: Cambridge
            post_code: CB22 7GG
            country_code: UK
# Disqus Comments
disqus:
    enabled: true
    shortname: Linaro
# Placeholder for Missing Images
placeholder: /assets/images/content/linaro-logo.png
