name: UpdateProjectsJSON

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.LINARO_BUILD_KEY }}
          path: website

      - name: Update projects data
        run: cd /srv/github-action-scripts && pipenv run python project_json_from_cloud.py
