name: UpdateProjectsJSON

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update projects data
        run: cd /srv/github-action-scripts && pipenv run python generate_project_json.py
